# Generated by Django 2.1.12 on 2019-10-04 00:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacionlocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('descripcion',),
            },
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dias',
                'verbose_name_plural': 'Dias',
                'ordering': ('descripcion',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, default='', max_length=1050, verbose_name='Pregunta')),
                ('respuesta', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Respuesta')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faq',
                'ordering': ('pregunta',),
            },
        ),
        migrations.CreateModel(
            name='HorarioLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de apertura')),
                ('horaFin', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de cierre')),
                ('estado', models.BooleanField(default=True)),
                ('dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Dias', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ('local',),
            },
        ),
        migrations.CreateModel(
            name='iplocalvisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ip')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, default='', max_length=50, verbose_name='Ruc')),
                ('razonsocial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nombreComercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('fotouno', models.ImageField(blank=True, null=True, upload_to='local/%Y/%m', verbose_name='Logo Comercial')),
                ('fotodos', models.ImageField(blank=True, null=True, upload_to='local/%Y/%m', verbose_name='Foto Local')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=500, null=True, verbose_name='telefono')),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo')),
                ('descripcion', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Descripcion')),
                ('visita', models.IntegerField(blank=True, default=0, null=True, verbose_name='Visita')),
                ('valortotal', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Calificación')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('documento',),
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('descuento', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='local/%Y/%m', verbose_name='Foto')),
                ('oferta', models.BooleanField(default=True, verbose_name='Oferta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Local', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Platos',
                'verbose_name_plural': 'Platos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(default='', max_length=20)),
                ('celular', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ('documento',),
            },
        ),
        migrations.AddField(
            model_name='local',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Usuarios', verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='iplocalvisita',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='horariolocal',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='calificacionlocal',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='calificacionlocal',
            name='votante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.Usuarios', verbose_name='Votante'),
        ),
    ]
