# Generated by Django 2.1 on 2019-10-06 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_auto_20191005_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='preciooferta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11),
        ),
    ]
