# Generated by Django 2.1 on 2019-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_platos_preciooferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='Oferta'),
        ),
    ]
