# Generated by Django 2.1.13 on 2019-10-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_local_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='visitante',
            field=models.BooleanField(default=False),
        ),
    ]
