# Generated by Django 2.1.12 on 2019-10-04 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiUsuarioTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla')),
                ('registroid', models.IntegerField(verbose_name='Registro Id')),
                ('registroname', models.CharField(max_length=100, verbose_name='Registro Name')),
                ('accion', models.CharField(choices=[('A', 'A'), ('M', 'M'), ('E', 'E')], max_length=10, verbose_name='Accion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estacion', models.CharField(max_length=100, verbose_name='Estacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria Usuario ',
                'verbose_name_plural': 'Auditorias Usuarios',
                'ordering': ('-fecha', 'hora'),
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ModuloGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('icono', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('grupos', models.ManyToManyField(to='auth.Group')),
                ('modulos', models.ManyToManyField(to='seguridad.Modulo')),
            ],
            options={
                'verbose_name': 'Grupo de Módulos',
                'verbose_name_plural': 'Grupos de Módulos',
                'ordering': ('prioridad', 'nombre'),
            },
        ),
    ]
